TRAIN:
  TARGET: 'omnipose'
  TRAIN_DATA_DIR: ['/home/chris/Dropbox (Partners HealthCare)/skoots-experiments/data/mitochondria/train/hide']
  VALIDATION_DATA_DIR: ['/home/chris/Dropbox (Partners HealthCare)/skoots-experiments/data/mitochondria/validation/hide']
  NUM_EPOCHS: 200
  SAVE_PATH: '/home/chris/Dropbox (Partners HealthCare)/bism/trained_model_files/testing'
  N_WARMUP: 50
  SAVE_INTERVAL: 10000
  SCHEDULER_T0: 1001
  STORE_DATA_ON_GPU: False
  TRAIN_BATCH_SIZE: 1
  TRAIN_SAMPLE_PER_IMAGE: [32]
  VALIDATION_BATCH_SIZE: 1
  VALIDATION_SAMPLE_PER_IMAGE: [6]
  LOSS_FN: 'omnipose'

AUGMENTATION:
  BRIGHTNESS_RATE: 0.0
  FLIP_RATE: 0.
  AFFINE_RATE: 0.0

MODEL:
  OUT_CHANNELS: 5
  MODEL: 'generic'
  OUTPUT_ACTIVATIONS: ['sigmoid', 'sigmoid', 'tanh', 'tanh', 'tanh']

SYSTEM:
  NUM_GPUS: 2