TRAIN:
  TARGET: 'omnipose'
  TRAIN_DATA_DIR: ['/home/chris/Dropbox (Partners HealthCare)/skoots-experiments/data/plant-stem/train']
  NUM_EPOCHS: 100
  SAVE_PATH: '/home/chris/Dropbox (Partners HealthCare)/bism/trained_model_files/testing'
  N_WARMUP: 5
  SAVE_INTERVAL: 10000
  SCHEDULER_T0: 1001
  STORE_DATA_ON_GPU: True
  TRAIN_BATCH_SIZE: 1
  LOSS_FN: 'omnipose'

AUGMENTATION:
  BRIGHTNESS_RATE: 0.0
  FLIP_RATE: 0.
  AFFINE_RATE: 0.0

MODEL:
  OUT_CHANNELS: 5
  MODEL: 'generic'
  OUTPUT_ACTIVATIONS: ['sigmoid', 'sigmoid', 'tanh', 'tanh', 'tanh']