TRAIN:
  TARGET: 'affinities'
  TRAIN_DATA_DIR: ['/home/chris/Dropbox (Partners HealthCare)/skoots-experiments/data/mitochondria/train/hide']
  VALIDATION_DATA_DIR: ['/home/chris/Dropbox (Partners HealthCare)/skoots-experiments/data/mitochondria/validation/hide']
  NUM_EPOCHS: 10000
  SAVE_PATH: '/home/chris/Dropbox (Partners HealthCare)/bism/trained_model_files/affinities/mitochondria'
  PRETRAINED_MODEL_PATH: ['/home/chris/Dropbox (Partners HealthCare)/bism/trained_model_files/affinities/mitochondria/Mar21_18-37-00_CHRISUBUNTU.trch']
  N_WARMUP: 10
  SAVE_INTERVAL: 500
  STORE_DATA_ON_GPU: True
  TRAIN_BATCH_SIZE: 4
  TRAIN_SAMPLE_PER_IMAGE: [32]
  VALIDATION_BATCH_SIZE: 4
  VALIDATION_SAMPLE_PER_IMAGE: [6]
  SCHEDULER_T0: 10001


